### ISSUE TITLE
Having sub navigation for non-resource groups

### ISSUE THREAD

**Issue by harhoo** [danielgtaylor/aglio#100]
I have some introductory text with subheadings, explaining various principles of the API and of the application. In apiary, these subheadings appear in the navigation. Using agilo, they don't. E.g. with the markup  

```
#Introduction

## Development Notes
Lorem ipsum

## REST-based
Lorem ipsum
```
Then there's nothing in the side navigation. If I do the following:

```
#Group Introduction

## Development Notes
Lorem ipsum

## REST-based
Lorem ipsum
```

I get Introduction in the side navigation. If I do

```
#Group Introduction

## Development Notes [/]
Lorem ipsum

## REST-based [/]
Lorem ipsum
```
 
It works as I'd like (i.e. Introduction as a side nav header and Development Notes as a link below it etc), but feels a bit (well, really) hacky. Is there an alternative to only resource groups appearing in the side navigation?

**Comment by harhoo** [comment]
(suspect you would need to pull the markdown out of the 'description' element produced by drafter and use that to (optionally?) produce the navigation, but that's well beyond my jade skills)

**Comment by danielgtaylor** [comment]
One possible implementation of this would be to pre-render the descriptions and create a hook to add any header anchors that get created as a new attribute on the resource/action/etc. Then, in the template when the navigation is being created, we read this attribute and create the necessary links. Thoughts?

**Comment by danielgtaylor** [comment]
@harhoo this is now implemented in the latest beta. Please give it a try via `npm install -g aglio@beta` and let me know what you think! It works for the API description and resource group descriptions, but not for resources/actions.

**Comment by danielgtaylor** [comment]
Closing as this is going into the 2.0 release very soon.
