### ISSUE TITLE
Data Structures

### ISSUE THREAD

**Issue by adammbalogh** [danielgtaylor/aglio#102]
I've just tried a blueprint with Data Structures in it, but aglio couldn't parse that. Do you plan to support Data Structures?

**Comment by danielgtaylor** [comment]
@adammbalogh this is a new feature of API Blueprint based on [MSON](https://github.com/apiaryio/mson). I plan to add support for it soon.

**Comment by danielgtaylor** [comment]
This is basically the same question as in #84, so I'm going to close this one. Please add any new comments there!
