### ISSUE TITLE
URI template in Action section ignored

### ISSUE THREAD

**Issue by hankipanky** [danielgtaylor/aglio#106]
URI templates as specified in an Action section are ignored in the output. Instead the URI from the Resource section is used.

Screenshot using [example 12](https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/12.%20Advanced%20Action.md) as input:
![screen shot 2015-05-08 at 12 30 53](https://cloud.githubusercontent.com/assets/1611513/7534768/2052408e-f57e-11e4-992c-754945d2d09d.png)

**Comment by whbath** [comment]
This looks to be fixed/merged into master, but pulling from NPM still has the bug? Has a new NPM been published? The package.json shows the same version as in NPM?

**Comment by hankipanky** [comment]
Thanks for fixing this!

**Comment by danielgtaylor** [comment]
Sorry I'll publish an updated version within the next day or two, since there are a small handful of changes that need to go out.

**Comment by it-ony** [comment]
I tried using version 2.0.0 and also 2.0.0-beta6, but the fix doesn't seem to be live yet. Which version do I need to use, or isn't published yet?

**Comment by it-ony** [comment]
Sorry, I didn't read the issue correctly. The custom template per resource works, but the URI parameters are not evaluated like specified here: https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-uri-templates.

I'll open a issue for this.
