### ISSUE TITLE
Custom Pages

### ISSUE THREAD

**Issue by vinkla** [danielgtaylor/aglio#107]
Is there a way to create custom pages for more generic documentation where you just write stuff? Like creating pages that will show up in the navigation without any API requests? Currently solved this by creating a `group`. Though, this only create a header page in the navigation. I would also like to add sub-pages with their own titles. Is this possible to do?

**Comment by danielgtaylor** [comment]
@vinkla it isn't possible at the moment unless you write a custom theme. I think that typically you would use some tool like a static site generator to write such extra documentation and then generate the API documentation using the same theme with `aglio`. I can see the appeal of not having to use a separate tool, however. Feel free to propose how this should work using only `aglio`.

**Comment by vinkla** [comment]
@danielgtaylor Okay, then I know. Thanks!
