### ISSUE TITLE
Long names in menu overlap icons

### ISSUE THREAD

**Issue by chesleybrown** [danielgtaylor/aglio#109]
Seems when you have long names in the menu, they overlap the icons. Should either concat or use a more fluid layout that isn't a fixed width. Or both.

![213361418-screen shot 2015-05-15 at 5 22 09 am copy](https://cloud.githubusercontent.com/assets/492166/7652662/6fe08ee2-fae9-11e4-813d-d2be6aa7b329.png)

This screenshot was taken using the `flatly-collapsible` theme.

**Comment by danielgtaylor** [comment]
This is now fixed in the latest olio theme updates. It'll be released shortly.
