### ISSUE TITLE
Add support for outputting the 'compiled' .md file.

### ISSUE THREAD

**Issue by GStipick** [danielgtaylor/aglio#115]
Aglio is great since we can use the '  ' feature to help separate resources that get rather large.

The only problem with this is that when trying to find and fix errors that aglio points out in the CLI, we do not have the compiled markdown document that aglio is using as a reference.

If there could be an option for parsing the extension of the outfile [-o outfile] to where if it is a .md it will just output the compiled .md file that Aglio creates after parsing the includes.

This will help not only with debugging, but also passing the md file to other programs that do not support 

Thanks,
  George S.

**Comment by danielgtaylor** [comment]
@GStipick I definitely want to add this feature, just haven't gotten around to it yet!

**Comment by danielgtaylor** [comment]
This was merged in with #116 and will be in the next release. Closing.
