### ISSUE TITLE
Double back slash during install

### ISSUE THREAD

**Issue by newtonianb** [danielgtaylor/aglio#118]
Finished generating code

``
Finished generating code
protagonist.vcxproj -> C:\prj\node_modules\aglio\node_modules\protagonist\build\Release\\protagonist.node``

It shows ``\\protagonist.node``

**Comment by danielgtaylor** [comment]
@newtonianb does this actually produce an error or is it just an annoyance to see the extra backslash? Either way it seems to be an issue upstream in protagonist.

**Comment by newtonianb** [comment]
It seems it installs fine I just noticed the last segment of the path has this double slash. Although I am encountering another issue and don't know if it is related
https://github.com/danielgtaylor/aglio/issues/117#issuecomment-108639676

**Comment by danielgtaylor** [comment]
Alright, I'm going to close this one for now as I don't think this is the problem, but I'll investigate things in the related issue.
