### ISSUE TITLE
No highlight for unfenced code blocks

### ISSUE THREAD

**Issue by automata** [danielgtaylor/aglio#119]
Markdown or other source codes included by
```
 <!-- include(code-examples/coffeescript/foo.coffee) -->
```
didn't get highlighted. Ideas?

**Comment by danielgtaylor** [comment]
Given the following included file:

    ```coffee
    class Foo
      constructor: (@id) ->
    ```

    Some other code:

        var x = 1;
        console.log(x * x);

    Yet more code:

    ```
    var y = 2;
    console.log(y * y);
    ```

You get this output:

![screen shot 2015-06-04 at 11 53 46](https://cloud.githubusercontent.com/assets/106826/7991895/69d80f1c-0ab0-11e5-9d37-aed0638ab7f1.png)

So it appears that indented code blocks (without the triple backticks) are not highlighted. I'll try and figure out why that is and if it can be changed.

**Comment by automata** [comment]
Thank you @danielgtaylor, wrapping included files with triple backticks is a good way around. It seems that included files are not highlighted: https://github.com/danielgtaylor/aglio/blob/master/src/main.coffee#L38

**Comment by danielgtaylor** [comment]
This is now implemented in the default theme. Release coming soon.
