### ISSUE TITLE
Missing styling for PATCH verb

### ISSUE THREAD

**Issue by nevir** [danielgtaylor/aglio#124]

**Comment by zdne** [comment]
Hey @nevir can you post a screenshot on how this look like without the styling? Thanks!

**Comment by nevir** [comment]
![screen shot 2015-06-23 at 11 17 08](https://cloud.githubusercontent.com/assets/41373/8313718/725d6360-1999-11e5-8d0d-c0940bfd2b28.png)

Not the worst, but a bit jarring :)

**Comment by danielgtaylor** [comment]
Whoops, good catch. This should be fairly easy to add.

**Comment by danielgtaylor** [comment]
This should now be fixed in the latest beta release. Install via `npm install -g aglio@beta`. This will become the next stable release soon.

**Comment by danielgtaylor** [comment]
Closing as this has been implemented, there is a way to install and use it with the beta, and it'll be released to stable soon.
