### ISSUE TITLE
Parsing error with dash in parameters names [1.18.0]

### ISSUE THREAD

**Issue by yellowiscool** [danielgtaylor/aglio#126]
Hi,

I want to document an API that have a dash in some parameters names. It looks like aglio (version 1.18.0) has a parsing error which such names.

### My input file

```markdown
# Books [/books]

- Parameters

    - book-id: (required, uri)

## By Id [GET]
```

### What I should get

![2015-07-13 15_18_43-api documentation](https://cloud.githubusercontent.com/assets/45740/8650414/e72c196e-2972-11e5-8184-995090926874.png)

### What I get
![2015-07-13 15_18_58-api documentation](https://cloud.githubusercontent.com/assets/45740/8650413/e6ffba9a-2972-11e5-8045-7a7d4ba52b0e.png)

**Comment by danielgtaylor** [comment]
@yellowiscool the parameters are generally describing some value in the URL, which is defined by a URI template. A URI template only allows a-z, A-Z, 0-9, and _ as valid characters, so you would need to percent-encode the value. The hex value for `-` is `%2D`:

```apib
# Books [/books/{book%2Did}]

- Parameters

    - book%2Did: (required, uri)

## By Id [GET]
```

The latest Aglio beta will render this properly. Install via `npm install -g aglio@beta`!

**Comment by yellowiscool** [comment]
Thank you for the percent-encoded value workaround. In my opinion, the dash character is a common and should be allowed but I understand the parsing issues. Feel free to close the issue.

About the parameter missing from the URI, it's because the API I'm documenting has the parameters in the HTTP headers…

**Comment by danielgtaylor** [comment]
Glad that it is working for you. I would also like to see it supported, and I could hack in workarounds to Aglio but then when you go to use other API Blueprint tools it would not work as expected. This is just a limitation of the RFC for the time being. Take care!
