### ISSUE TITLE
The members section doesn't render encoded hyphens (%2D) and the description is missing

### ISSUE THREAD

**Issue by tciuro** [danielgtaylor/aglio#137]
Check the following snippet:

    + filter (optional, string) ... blah
        + Members
            + non%2Dfoo - description goes here
            + with%2Dbar%2Dresults - description goes here

Rendered results:

![screen shot 2015-07-22 at 11 40 05 am](https://cloud.githubusercontent.com/assets/412899/8833961/70e10b16-3066-11e5-8dff-5218a0f2d37a.png)

The spec seems to imply that each choice can contain a description:

	+ <parameter name>: `<example value>` (<type> | enum[<type>], required | optional) - <description>

	    <additional description>

	    + Default: `<default value>`

	    + Members
	        + `<enumeration value 1>` - <enumeration description 1>
	        + `<enumeration value 2>` - <enumeration description 2>
	        ...
	        + `<enumeration value N>` - <enumeration description N>

Please note that the URI is being rendered fine if it contains encoded hyphens (%2D).

**Comment by tciuro** [comment]
I just discovered that if I wrap the string with the hyphen using back ticks, it gets rendered well:

	+ filter (optional,enum[string])
		+ Members
			+ `non-foo` - This is A
			+ `with-bar-results` - This is B

![screen shot 2015-07-22 at 12 05 44 pm](https://cloud.githubusercontent.com/assets/412899/8834607/04c1fa40-306a-11e5-90e2-b4d0d5b1a1b0.png)

Not that `This is A` and `This is B` are not being rendered at all.

**Comment by danielgtaylor** [comment]
@tciuro Thanks for noticing this. I'll be fixing the `%`-encoded display of choices shortly. As for the choice description, the default theme has no way of displaying those at the moment. This may be a feature I look into adding in the future.
