### ISSUE TITLE
There is no margin between the overviews and the first resource group

### ISSUE THREAD

**Issue by huiyiqun** [danielgtaylor/aglio#141]
I have tried to compile apib with latest aglio from github, without any additional arguements except `-i` and `-s`.

It looks strange.

![screenshot_2015-07-28_16-50-30](https://cloud.githubusercontent.com/assets/3468160/8927248/a43daef6-3548-11e5-89f5-25597864f161.png)

**Comment by danielgtaylor** [comment]
@huiyiqun thanks for reporting this bug! It should be fixed in the latest release of the default theme (the `aglio-theme-olio` package). You can get it by re-installing Aglio, e.g. `npm install -g aglio`.

**Comment by huiyiqun** [comment]
Thanks. I will try.
