### ISSUE TITLE
GET requests should not show "empty request message-body (warning code 6)"

### ISSUE THREAD

**Issue by tciuro** [danielgtaylor/aglio#142]
Consider the following snippet:

		# Group Some Stuff
 
		## Retrieve Some Stuff [/something/{id}/foo{?stuff}]

		### Retrieve Some Stuff [GET]

		+ Parameters

		    + id (required, string) ... Some ID.
		    + stuff (optional, boolean) ... Whether to include stuff or not.

		+ Request /something/123/foo
			
		+ Response 200

		    + Body

		            {
		              "status": true
		            }
            
		+ Request /something/123/foo?stuff=false
			
		+ Response 200

		    + Body

		            {
		              "status": false
		            }

Reference: [multiple transaction examples](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#example-multiple-transaction-examples)

The issue I see is:

    >> Line 1112: empty request message-body (warning code 6)
    >> Line 1186: empty request message-body (warning code 6)

The problem I see is that this is a GET request, so there is no body.

**Comment by danielgtaylor** [comment]
Confirmed that this is happening, but it's in the parser so I've opened an issue there. You can follow along here:

https://github.com/apiaryio/snowcrash/issues/342
