### ISSUE TITLE
Code blocks (example & schema) don't support text wrapping

### ISSUE THREAD

**Issue by seglo** [danielgtaylor/aglio#152]
When a line is longer than the width of the code div it does not overflow/wrap on to the next line.  The only way to see the actual text is to copy & paste it out of the HTML document.

![aglio-nowrap](https://cloud.githubusercontent.com/assets/1148412/9235355/4cc814b6-410c-11e5-980a-d0cc311e5de2.PNG)

Is there any way to make this text wrap via configuration or some other means?

**Comment by danielgtaylor** [comment]
@seglo thanks for the bug report. If you update to the latest version I've modified the style to add scrollbars automatically. If you would prefer wrapping, you can do something like this:

**my-style.less**
```less
pre {
  white-space: pre-wrap;
{
```

Then run like so:

```sh
aglio -i input.apib -o output.html --theme-style default --theme-style ./my-style.less
```

Hope this helps!

**Comment by seglo** [comment]
Thanks a lot @danielgtaylor .  Works like a charm.  Impressive response time! :+1:

**Comment by HenkPoley** [comment]
For future reference, it's of course:
```css
pre {
  white-space: pre-wrap;
}
```

{ -> }
