### ISSUE TITLE
boolean type in Data Structures prevents Request Body

### ISSUE THREAD

**Issue by jonwurtzler** [danielgtaylor/aglio#153]
When I use the boolean type for a field in a Data structure, the generated response no longer has a Body section.

If I have the following:

```
# Group Test
## Test a Call [/test]
### Run the Test [PUT]

+ Request (application/json)
  + Attributes (TestObject)

# Data Structures
## TestObject (object)
+ switch: `1` (boolean, required) - Boolean object.
```

It will compile just fine, but the Request Body section will be missing.  Headers and Schema will be there and look just fine.  If I change the boolean type to a number type, the Body section will return.

**Comment by kylef** [comment]
Hi @jonwurtzler, the sample value you've provided for your `switch` property is a number and not a boolean value.

Simply switching this to be a boolean value such as `true` or `false` should make this work.

```apib
# Data Structures
## TestObject (object)
+ switch: true (boolean, required) - Boolean object.
```

**Comment by jonwurtzler** [comment]
Sure enough, that works just fine.  I feel rather foolish.

Thank you for the update.
