### ISSUE TITLE
Json schema under body response is not correct

### ISSUE THREAD

**Issue by benoittgt** [danielgtaylor/aglio#156]
Hello

I'm having a problem. When writing Post/Update documentation. Schema is render below request body (it's ok) but also under body response. And that's not correct. It takes the definition of the attributes written for the request body.

Live demo : http://appaloosa-store.com/api#users-user-post

![image](http://i.imgur.com/wsngn9R.png)

Is it a normal behavior?

**Comment by zdne** [comment]
@benoittgt I believe this may be related to #155

**Comment by danielgtaylor** [comment]
@benoittgt this does look like a bug. I'm going to look into it and see if I can track down what is happening.

**Comment by danielgtaylor** [comment]
@benoittgt please have another look with the latest version. These issues should now be fixed!

**Comment by benoittgt** [comment]
Thanks a lot @danielgtaylor and @zdne for the job done.
