### ISSUE TITLE
Is there a way to define variables in the markdown?

### ISSUE THREAD

**Issue by mmadson** [danielgtaylor/aglio#158]
Perhaps this is outside aglio's scope, but I was wondering if there was a way to declare variables in the api blueprint markdown.

**Comment by zdne** [comment]
@mmadson no, not really. May I ask what would be the use case?

**Comment by mmadson** [comment]
Our product is distributed a number of different ways under different names. While each distribution has the same web service API it would be great to generate the docs like so:

${product.name} Web Service API
... more blueprint markdown

 aglio -Dproduct.name=LeCoolProduct

**Comment by kylef** [comment]
You could perhaps use some kind of template language like [Stencil](http://github.com/kylef/Stencil) or  [Jinja2](https://en.wikipedia.org/wiki/Jinja_(template_engine)#Example) to add a preprocessor step to provide additional variable substitution and logic. As such:

```apib
HOST: https://{subdomain}.cocoapods.org/

# {name} API

{% if has_admin_feature %}
## Users Collection [/users]
### View all users [GET]
...
{% endif %}
```

Then to render the template into an API Blueprint:

```python
from jinja2 import Template

print(Template(my_api).render(
    name='Metrics',
    subdomain='metrics',
    has_admin_feature=True
))
```

You would then pass your templated API Blueprint though your script to render it into a full API Blueprint to pass to Aglio.

[Contentful](https://github.com/contentful/slash-developers#usage) are doing similar preprocessing of their API Blueprints from a custom [Makefile](https://github.com/contentful/slash-developers/blob/master/apiary/Makefile) which concatenates multiple files into one before uploading to Apiary.

**Comment by danielgtaylor** [comment]
:+1: to @kylef. I think this is outside the scope of Aglio and should be accomplished with your template language of choice before running through Aglio. @mmadson let me know if you need specific help with this.
