### ISSUE TITLE
HTML entities are not rendered in group names

### ISSUE THREAD

**Issue by winniehell** [danielgtaylor/aglio#160]
Using aglio `2.0.4`, the following
```markdown
# Group Foo&trade;

## Bar &hearts;
```
leads to 
![toc](https://cloud.githubusercontent.com/assets/1652293/9546674/f8417816-4d94-11e5-9f4c-ffc1dc64d7c6.PNG)
![doc](https://cloud.githubusercontent.com/assets/1652293/9546675/fa06ce44-4d94-11e5-8efa-b4df5754fcea.PNG)

**Comment by danielgtaylor** [comment]
Thanks for reporting!

**Comment by danielgtaylor** [comment]
Fixed in the Olio theme 1.2.1 release.

**Comment by winniehell** [comment]
Thanks, that was fast! :+1: :sparkles: 

![toc](https://cloud.githubusercontent.com/assets/1652293/9613899/88e99ba8-50ee-11e5-82ff-785ecb5a3879.png)
![doc](https://cloud.githubusercontent.com/assets/1652293/9613910/9f50d974-50ee-11e5-9447-b969b8ef7185.png)
