### ISSUE TITLE
Update Readme to mention --include-path

### ISSUE THREAD

**Issue by acoulon99** [danielgtaylor/aglio#166]
After adding the `--include-path` flag, our aglio implementation broke until after we read the changelog. It would be nice to see a mention of the new flag on the Readme or in another easily visible location.

**Comment by danielgtaylor** [comment]
@acoulon99 thanks, I hadn't realized the broken behavior. It is now restored in the 2.1.1 release and I've added some extra documentation around the option. Let me know if there are any other issues!
