### ISSUE TITLE
where is default-multi option?

### ISSUE THREAD

**Issue by sangar82** [danielgtaylor/aglio#169]
Is no longer exist the default-multi option ?? 

I've seen, in this version we can use themes. Are there some theme equal to the default-multi?

Thanks !!

**Comment by danielgtaylor** [comment]
@sangar82 the option was removed in the 2.0 release. As far as I know, there is no theme yet that is similar. I am hard at work on other features (like supporting [MSON](https://github.com/apiaryio/mson#readme)) but would love to see someone contribute more themes!

If you would like to continue using the `default-multi` theme you can downgrade to Aglio 1.x for the time being, e.g. `npm install -g aglio@1` but you won't get the new features from the 2.x releases.
