### ISSUE TITLE
Aglio can not run with nodejs v4

### ISSUE THREAD

**Issue by cong88** [danielgtaylor/aglio#172]
I upgraded nodejs to v4 and aglio stop working. Can you make it compatible with nodejs v4.

Thanks.

This is my error log:

30787 verbose stack Error: protagonist@0.20.1 install: `node-gyp rebuild`
30787 verbose stack Exit status 1
30787 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
30787 verbose stack     at emitTwo (events.js:87:13)
30787 verbose stack     at EventEmitter.emit (events.js:172:7)
30787 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
30787 verbose stack     at emitTwo (events.js:87:13)
30787 verbose stack     at ChildProcess.emit (events.js:172:7)
30787 verbose stack     at maybeClose (internal/child_process.js:817:16)
30787 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
30788 verbose pkgid protagonist@0.20.1
30789 verbose cwd /var/log
30790 error Linux 3.13.0-32-generic
30791 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "aglio" "-g"
30792 error node v4.1.0
30793 error npm  v3.3.4
30794 error code ELIFECYCLE
30795 error protagonist@0.20.1 install: `node-gyp rebuild`
30795 error Exit status 1
30796 error Failed at the protagonist@0.20.1 install script 'node-gyp rebuild'.
30796 error This is most likely a problem with the protagonist package,
30796 error not with npm itself.
30796 error Tell the author that this fails on your system:
30796 error     node-gyp rebuild
30796 error You can get their info via:
30796 error     npm owner ls protagonist
30796 error There is likely additional logging output above.
30797 verbose exit [ 1, true ]

**Comment by jmdacruz** [comment]
This is actually a problem in protagonist, as pointed out in https://github.com/apiaryio/protagonist/issues/91 and in https://github.com/apiaryio/protagonist/issues/81

**Comment by kentchiu** [comment]
downgrade node version to 0.12.7 works for me

**Comment by cong88** [comment]
Thanks guys. need to wait change of protagonist

**Comment by humanjack** [comment]
@cong88  "Protagonist 1.1.0 now supports Node 3 and Node 4."
https://github.com/apiaryio/protagonist/releases/tag/1.1.0
You can open this issue again

**Comment by kylef** [comment]
@humanjack Aglio master already pins to ^1.0.0 of protagonist so Aglio (master) will already work with this version of Protagonist.

**Comment by danielgtaylor** [comment]
@cong88 @humanjack @jmdacruz @kentchiu @kadishmal Aglio 2.2.0 now supports Node.js 4.x, so please give it another try!
