### ISSUE TITLE
No support for MSON 'One of'

### ISSUE THREAD

**Issue by seattlevine** [danielgtaylor/aglio#174]
Attributes listed under a 'One of' section do not render.
Given:
+ Attributes
    + container - Container for name/reference of pool to use/create.
        + One of
            + itemA: my_item (string) - An item of type A.
            + itemB: my_other_item (string) - An item of type B.
        + itemC: my_third_item (string) - An item of type C.

Only itemC is rendered

**Comment by danielgtaylor** [comment]
@seattlevine this is a limitation of the [Drafter.js](https://github.com/apiaryio/drafter.js) depedency, which is being replaced by an updated tool that will hopefully fix many of these types of issues. You can already play with the newer output if you take a look at [Protagonist](https://github.com/apiaryio/protagonist) version 1.x, but it'll be at least a few weeks until that output is in Aglio.

**Comment by seattlevine** [comment]
Great thanks. No problem for us if it's fixed in a few weeks or even months.

**Comment by danielgtaylor** [comment]
@seattlevine please have another look. The default theme `olio-theme-1.6.0` release now includes some support for `One Of` MSON members. In the generated JSON examples, the first of the `One Of` items is always chosen. In the generated JSON Schema all options are shown and limited with a "not both required" rule. Please let me know if you run into other issues!

**Comment by brendensoares** [comment]
@danielgtaylor The theme does not work for nested property lists such as:
```
+ Attributes
    + One Of
        + Properties
            + a
            + b
        + Properties
            + c
            + d
```

The latest theme [appears to go too deep](https://github.com/danielgtaylor/aglio/blob/olio-theme/src/example.coffee#L42) and only displays the first property of the first option (ie. `a`).

Setting the `DRAFTER_EXAMPLES=1` env var works around this by skipping the theme's logic in favor of the correct Drafter example.

It would also be great if aglio's default theme support the display of ALL options for `One Of`, not just the first one.
