### ISSUE TITLE
Can't npm install aglio 

### ISSUE THREAD

**Issue by jvrsantacruz** [danielgtaylor/aglio#175]
Hi,

I can't install aglio via `npm`. I've searched through closed issues both in the aglio and protagonist projects and all these issues seem to have been addressed and fixed several months ago.

```
node --version
v4.1.1

npm --version
3.3.4

python --version
Python 2.7.10

uname -a
Linux tlap 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux
```
When I try to install aglio via npm, I get the following error:

```
npm install aglio
(...) installing and compiling
In file included from /usr/include/c++/5.2.0/memory:81:0,
                 from ../drafter/ext/snowcrash/ext/markdown-parser/src/MarkdownNode.h:13,
                 from ../drafter/ext/snowcrash/src/Blueprint.h:16,
                 from ../src/protagonist.h:7,
                 from ../src/annotation.cc:1:
/usr/include/c++/5.2.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
protagonist.target.mk:135: recipe for target 'Release/obj.target/protagonist/src/annotation.o' failed
make: *** [Release/obj.target/protagonist/src/annotation.o] Error 1
make: Leaving directory '/home/jsl/taric/tariczilla/node_modules/protagonist/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.6-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jsl/taric/tariczilla/node_modules/protagonist
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:protagonist protagonist@0.20.1 install: `node-gyp rebuild`
npm WARN install:protagonist Exit status 1
```

I understand there is a high probability that this compile failure is related to my node.js version, if so I have no much knowledge of node and I would be interested in knowing how could I manage several node versions within the same installation, very much like I do with python or ruby.

Thank you.

**Comment by danielgtaylor** [comment]
@jvrsantacruz one of the dependencies (the API Blueprint parser) does not yet support Node.js 4.x. It is in the process of being updated, but until that is complete you will need to use an older version of Node.js.

**Comment by jvrsantacruz** [comment]
I've used [nvm](https://github.com/creationix/nvm) and successfully installed aglio using node v0.12.
Thank you.

**Comment by dsernst** [comment]
You can get around this issue by doing `npm install --save-dev aglio` while on node 0.12, instead of installing it globally. Then invoke it with either `node_modules/.bin/aglio` or just `aglio` from within an `npm run-script`.

As long as the module is compiled while on node 0.12, it still works fine even after switching to `nvm use 4`, because the projects' `node_modules/` don't get blown away.

**Comment by jvrsantacruz** [comment]
Thanks! I'll do it this way to avoid setting up the environment each time.

**Comment by danielgtaylor** [comment]
@jvrsantacruz Node.js 4.x should now be supported in the latest Aglio release!
