### ISSUE TITLE
Request parameters completely broken

### ISSUE THREAD

**Issue by m-baumgartner** [danielgtaylor/aglio#181]
Request parameters aren't shown anymore.

Steps to reproduce : 
* Git clone the current repo
* Execute `aglio` on the current example.apib file (in my case using the docker image)
* Host it (in my case using a python `Simplehttpserver` on my os x env)

No parameters details are displayed.

**Comment by kylef** [comment]
@m-baumgartner Could you please clary which commit or release of Aglio you are using?

Thanks.

**Comment by m-baumgartner** [comment]
Hm, apparently the [dockerimage](https://github.com/davidonlaptop/docker-aglio/blob/v1.18.0/aglio-1.18/Dockerfile) i'm using is targeting `aglio@1.18.0` This might be the source. I'll try with aglio@latest

**Comment by m-baumgartner** [comment]
Much better indeed :). Sorry
