### ISSUE TITLE
enum syntax not work

### ISSUE THREAD

**Issue by jk2K** [danielgtaylor/aglio#192]
```
 type (enum[string]) - upload type
		+ Members
			+ `avatar` - avatar
			+ `gallery` - gallery
```
version: 
aglio 2.2.0
olio 1.4.0

**Comment by danielgtaylor** [comment]
@jk2K thanks for reporting. This seems to be an upstream issue in the [Drafter](https://github.com/apiaryio/drafter) parser library.

**Comment by danielgtaylor** [comment]
@jk2K please try the latest olio theme 1.5.0 (you can just reinstall Aglio to get it). The rendering of enumerated types should be fixed now, and it should choose the first option for the examples. In your example above, that means you would see `"type": "avatar"` in the JSON for you example MSON above.

**Comment by jk2K** [comment]
work fine, thanks
