### ISSUE TITLE
Option to disable emoticons

### ISSUE THREAD

**Issue by jk** [danielgtaylor/aglio#194]
I could not find an option to disable the replacement of emoticons. In my API blueprint I describe some terms like `Facet:Position…` were the `:P` gets replaced by an emoticon. I think it's obvious that this not the intended behavior. There're a couple more emoticons which were replaced.

![Screenshot of emoticons](https://dl.dropboxusercontent.com/s/vgl93ud1i6o5aa9/2015-11-11%20at%2010.02.png)

Perhaps you would like introduce a CLI parameter like `--disable-emoticons`?

**Comment by kylef** [comment]
@jk Perhaps it would make sense to wrap these strings in code blocks:

```apib
- `Facet:PositionIndustry.Name`: industry (german: "Branche") name
```

This would atleast provide you with a quick workaround.

**Comment by jk** [comment]
@kylef Thanks, that's working for a workaround.

**Comment by danielgtaylor** [comment]
@jk the latest release of the Olio theme (1.6.0) now provides an option to disable emoji support via `--no-theme-emoji`. Sorry about that!

**Comment by truebit** [comment]
Now there is only option in help message with `--theme-emoji`, it cannot make users got the `--no-theme-emoji` idea.
Maybe in help message, we should say that there is a `--no-theme-emoji` whose default value is `false`
