### ISSUE TITLE
Extended data structures are not rendered properly

### ISSUE THREAD

**Issue by robbinjanssen** [danielgtaylor/aglio#197]
When rendering docs for the following example, the `Project` is not rendered properly in the `body`. At first I thought this was a bug, but this should be possible. See https://github.com/apiaryio/api-blueprint/issues/284

```apib
FORMAT: 1A
HOST: https://test.api.com/

# Test API
Hi, welcome to the API!

# Group Projects
Wow, we are using projects!

### Retrieve single project [GET /projects/{id}]
+ Parameters
    + id: `5` (string, required)

+ Response 200 (application/json)
    + Attributes (object)
        + data (ProjectData, required)

# Data Structures

## ProjectLink (object) 
+ self: `https://test.api.com/projects/5` (string, required)

## ProjectIdentifier (object)
+ type: `projects` (string, required)
+ id: `5` (string, required)

## ProjectData (ProjectIdentifier)
+ attributes (object, required)
    + number: `PRO-5` (string) - A readable identifier for employees to refer to projects.
+ links (ProjectLink, required)

```

Returned `body`:

```json
{
  "data": {
    "type": "projects",
    "id": "5"
  }
}
```

**Comment by robbinjanssen** [comment]
As stated in https://github.com/apiaryio/api-blueprint/issues/284#issuecomment-156080084 a fix could be:
```apib
## ProjectData (object)
+ Include ProjectIdentifier
+ attributes (object, required)
    + number: `PRO-5` (string) - A readable identifier for employees to refer to projects.
+ links (ProjectLink, required)
```

This should output (at least in Apiary.io):
```json
{
  "data": {
    "type": "projects",
    "id": "5"
    "attributes": {
      "number": "PRO-5"
    },
    "links": {
      "self": "https://test.api.com/projects/5"
    },
  }
```

Aglio does pick up the Include, but renders them at the bottom:

```json
{
  "data": {
    "attributes": {
      "number": "PRO-5"
    },
    "links": {
      "self": "https://test.api.com/projects/5"
    },
    "type": "projects",
    "id": "5"
  }
```

**Comment by danielgtaylor** [comment]
@robbinjanssen thanks for reporting this bug - this is fantastic. I'm glad to see people seriously using MSON!

I'm going to look into fixing this as soon as I can. I've just had my wisdom teeth surgically removed (one was encased in my jaw bone) under general anesthesia so I'm pretty out of it today. Open source developers are only human, too :sweat_smile:

**Comment by robbinjanssen** [comment]
Thanks @danielgtaylor, and good luck with your recovery, removing those wisdom teeth can be pretty unpleasant.

**Comment by danielgtaylor** [comment]
@robbinjanssen please try olio-theme-1.6.1 which should fix these issues. Both your examples should now work properly and both the example and schema generator now use the new inheritance implementation. Please let me know if I've missed any other common use cases for MSON structures!

**Comment by robbinjanssen** [comment]
Can confirm that 1.6.1 fixes the problem! Thanks @danielgtaylor, great work!
