### ISSUE TITLE
Show context when printing warnings

### ISSUE THREAD

**Issue by JanStevens** [danielgtaylor/aglio#202]
Hello,

When using include tags the warnings don't reference the included file but rather the concated result. For example my main api has just 4 include tags and I have a warning on line 504. I now have no clue where to look.

I've created a [PR](https://github.com/nnnnathann/gulp-aglio/pull/10) for the `gulp-aglio` package that does include the context of the error. I think this should be added in the main Aglio package, an example:

![screen shot 2015-11-30 at 10 53 18](https://cloud.githubusercontent.com/assets/1540483/11469617/f8974662-9757-11e5-9e52-1a80fff0b7b8.png)

I think this could be done easily in the bin file, optionally It would be better if we had a reference to the original source file.

Related to: https://github.com/danielgtaylor/aglio/issues/96 but this might be a temp solution?

Regards,

**Comment by danielgtaylor** [comment]
Love it! We should definitely add this.
