### ISSUE TITLE
Olio-theme cannot display empty strings as example value

### ISSUE THREAD

**Issue by robbinjanssen** [danielgtaylor/aglio#203]
I've noticed that the `olio-theme` uses custom [defaultValues](https://github.com/danielgtaylor/aglio/blob/olio-theme/src/example.coffee#L23) if no example value is provided, but for some of my markdown I want an empty string as an example value. For example in the an optional description value.

I've tried the following use cases
#### Empty string in backticks

``` apib
+ description: `` (string, optional) - Optional string
```

``` json
{
  "description": "``"
}
```
#### A space as example value

``` apib
+ description:   (string, optional) - Optional string
```

``` json
{
  "description": "Hello, world!"
}
```
#### Empty string in single quotes

``` apib
+ description: '' (string, optional) - Optional string
```

``` json
{
"description": "''"
}
```
#### Empty string in double quotes

``` apib
+ description: "" (string, optional) - Optional string
```

``` json
{
"description": "\"\""
}
```

Any suggestions or ideas on how this could be achieved / implemented?:)

**Comment by brendensoares** [comment]
Nice question and details.

I had the same issue and i just stumbled onto a solution after searching docs and such. The solution is a **space character surrounded by back ticks**:

```
+ description: ` ` (string, optional)
```

generates:
```
{
    "description": ""
}
```
