### ISSUE TITLE
UriTemplate + query params not rendered correctly

### ISSUE THREAD

**Issue by AlexZeitler** [danielgtaylor/aglio#205]
I tried to use this template:

```### Get Configuration [GET /configuration{?color}]```

I would expect something like this:

```http://expample.org/configuration{?color} ```

But the result is

```http://expample.org/configuration ```

**Comment by danielgtaylor** [comment]
@AlexZeitler did you also document the parameter? For example:

```apib
### Get Configuration [GET /configuration{?color}]
+ Parameters
    + color (string) - Specify the configuration color
```

Aglio filters out any undocumented parameters, letting you put all possible parameters in the resource URI template and documenting the relevant parameters in each action.

**Comment by AlexZeitler** [comment]
@danielgtaylor Thanks, I forgot to document the parameter. No it works as expected. :+1:
