### ISSUE TITLE
Same links for all resources within a group

### ISSUE THREAD

**Issue by lsmag** [danielgtaylor/aglio#21]
Hello,

We started using Aglio yesterday, and we noted that all resources within a group have the same link, including its target's ids. For example, considering this input:

    Group Foobar
    ============

    ...

    GET /resources/
    --------------

    ...

    + Response 200 (application/json)

            ...

    GET /resources/?limit={page_limit}
    ---------------------------------

    ...

    + Response 200 (application/json)

            ...

    GET /resource/{id}/
    ------------------

    ...

    + Response 200 (application/json)

            ...

Aglio generates:

    
    <div class="list-group">
        <a href="#foobar" class="list-group-item heading">Foobar</a>
        <a href="#foobar-" class="list-group-item">
            <i class="fa fa-arrow-circle-down"></i>&nbsp;GET /resources/
        </a>
        <a href="#foobar-" class="list-group-item">
            <i class="fa fa-arrow-circle-down"></i>&nbsp;GET /resources/?limit={page_limit}
        </a>
        <a href="#foobar-" class="list-group-item">
            <i class="fa fa-arrow-circle-down"></i>&nbsp;GET /resource/{id}/
        </a>
    </div>

    
    <h4 id="foobar-">
        Foobar&nbsp;
        <a href="#foobar-"><i class="fa fa-link"></i></a>
    </h4>

    
    <section id="foobar--get" class="panel panel-info">

I didn't read the source code, but it seems like a bug on group rendering. If it's confirmed it is a bug, I can make a fork and work on it.

**Comment by adamgross42** [comment]
I'm running into this issue as well, would be great to support this.

**Comment by danielgtaylor** [comment]
This is on my list of things to address for the theme revamp I'm currently working on. See https://github.com/danielgtaylor/aglio/issues/33#issuecomment-70533061 for more info.

**Comment by danielgtaylor** [comment]
Please try installing `sudo npm install -g aglio@beta` and let me know if you have the same issues.

**Comment by danielgtaylor** [comment]
Confirmed that this is still an issue with the latest theme. I'll see about fixing this.

**Comment by danielgtaylor** [comment]
This should now be fixed in the latest theme update to the beta.
