### ISSUE TITLE
Can't install on ubuntu 14.04

### ISSUE THREAD

**Issue by bitnumus** [danielgtaylor/aglio#211]
Hi, the docs here do not give any information on package versions and such, and it seems this is important. I'm just getting streams of errors when installing on ubuntu, i've installed nodejs from the latest PPAs using "curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -"

What should i be doing?

I won't paste all my logs, they are full with things like:

warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             std::auto_ptr<Elements> m_elements;

**Comment by shaun-ba** [comment]
.
