### ISSUE TITLE
Segmentation fault when more than 16 data structures

### ISSUE THREAD

**Issue by wadey** [danielgtaylor/aglio#213]
I am experiencing a segmentation fault when I try to process a file with more than 16 data structures. This is using Node v4.2.4 and the latest version of aglio 2.2.0 and protagonist 1.2.3.

The example file, the gdb backtrace and full `npm ls` details are attached to this gist:

- https://gist.github.com/wadey/c16ea2040d3aeecd8e77

If you reduce the test file from 17 data structures to 16 data structures, the segmentation fault does not occur.

Let me know if I can provide more details.

**Comment by jordan-wright** [comment]
:+1: I'm having the same exact issue. My .apib has 21 data structures, so aglio is failing with a segmentation fault.

It looks like it might have to do with ```drafter```?

**Comment by jordan-wright** [comment]
Confirmed this looks to be protagonist parsing that is causing this issue. I filed an issue on their project for this.

**Comment by w-vi** [comment]
Cheers @jordan-wright . Please follow  drafter issue https://github.com/apiaryio/drafter/issues/207 as this is the same bug, once drafter is fixed the protagonist will be fixegd as well.

**Comment by wadey** [comment]
This was fixed by protagonist 1.2.4: https://github.com/apiaryio/protagonist/issues/116

Re-installing aglio so that it fetches the latest version of protagonist is all that is necessary to fix this issue on the aglio side.
