### ISSUE TITLE
Protagonist 1.2.4 is broken

### ISSUE THREAD

**Issue by aichholzer** [danielgtaylor/aglio#214]
Not sure who can fix the issue faster but, in the meantime, this

```
"protagonist": "^1.2.2",
```

should be change to:

```
"protagonist": "1.2.3",
```

`Drafter` is missing in the current protagonist version, thus the install will fail.
See http://ab.je/8a

**Comment by kylef** [comment]
Resolved by [protagonist 1.2.5](https://github.com/apiaryio/protagonist/releases/tag/v1.2.5).
