### ISSUE TITLE
aglio's includes - option to generate new full API blueprint document

### ISSUE THREAD

**Issue by PavelPolyakov** [danielgtaylor/aglio#217]
Hi,

aglio supports it's own ```include``` format:
https://github.com/danielgtaylor/aglio#including-files

It's good, because it allows us to separate the blueprint document.

However, most of the API blueprint software does not support this format.
For example, mock server generator https://github.com/Aconex/drakov , expect to have everything in one file.

Is there an option to be able to export the full API blueprint document after includes are parsed by aglio?
If not - could we request such?

Regards,

**Comment by danielgtaylor** [comment]
@PavelPolyakov there is an option for this, called `compile`:

```sh
aglio -i input.apib --compile -o full.apib
```

Please let me know if it isn't working!

**Comment by PavelPolyakov** [comment]
@danielgtaylor 
Thanks,

I would say ```--compile``` works, however drakov fails:
![image](https://cloud.githubusercontent.com/assets/839290/12300762/338ad472-ba1d-11e5-9f02-6c3ecd42a5ed.png)

I don't see anything strange in the result file though.
