### ISSUE TITLE
Expanded vs. collapsed menu

### ISSUE THREAD

**Issue by aichholzer** [danielgtaylor/aglio#219]
When serving my documentation, the items in the navigation menu on the left are randomly collapsed or expanded. Is there a way to make `aglio` serve this consistently? - For example, I would like all navigation sections to always be collapsed at the start.

**Comment by PavelPolyakov** [comment]
I would like to have it expanded.

I think it starts collapse when you have too many things in your list.
That was my observation, unfortunately haven't found this configurable.

**Comment by aichholzer** [comment]
@PavelPolyakov In my case it seems to be completely random; one time the smaller navigation blocks are collapsed, sometimes expanded. Tried finding a setting for this as well... No luck, hence the question.

**Comment by sangar82** [comment]
same here! completely random1!

**Comment by leewaa** [comment]
Yep, totally random! Anything happening here ?

**Comment by danhawkes** [comment]
This is due to the autoCollapse() function here:
https://github.com/danielgtaylor/aglio/blob/c52a482e5392849de12ce1cf43245ad66da44745/templates/scripts.js#L140
Unfortunately can't see a means of configuring it that doesn't involve cloning the theme.

**Comment by aichholzer** [comment]
Over two years have passed and no solution/suggestion... Marking this as closed/dead.
