### ISSUE TITLE
Special characters in request actions

### ISSUE THREAD

**Issue by joseph-norman** [danielgtaylor/aglio#224]
Hi guys,

Forgive me if this has already been answered but I wasn't able to find a similar issue. Running into a problem adding formatting data to examples in attributes using special characters.

For example, the following
```
+ question (string, ```What is the amount of £?```) - The question
```

Renders correctly. However this:
```
+ question (string, `What is the amount of £?`) - The question
```
Returns what looks like character encoding in place of the actual symbol (i.e "What is the amount of B#?").

Thanks - if it is indeed a bug I'd be more than happy to raise a PR for it.

**Comment by joseph-norman** [comment]
Update: ignore me, its to do with my own rendering setup.

**Comment by kylef** [comment]
Btw, this should be as following in MSON (if you're having problems with it):

```apib
+ question: `What is the amount of £?` (string) - The question
```

**Comment by joseph-norman** [comment]
Ah, thanks - perfect. Appreciated.
