### ISSUE TITLE
What does --compile do?

### ISSUE THREAD

**Issue by curtisblackwell** [danielgtaylor/aglio#230]
I'm new to both API Blueprint and aglio. I was playing around with the options, but `-c` doesn't seem to do anything different for me.

**Comment by danielgtaylor** [comment]
@curtisblackwell if you are using multiple files via the include directive, then the `-c` option will output the full file with all the the include directives replaced with the included file content inline. It can be used to generate the full file for other tools like Dredd or to be uploaded to Apiary.
