### ISSUE TITLE
Emojis are not display in left column.

### ISSUE THREAD

**Issue by benoittgt** [danielgtaylor/aglio#235]
Hello

It seems emoji are properly display in the main doc but not in the left column.

<img width="566" alt="capture d ecran 2016-02-15 a 10 57 18" src="https://cloud.githubusercontent.com/assets/8417720/13045324/edf697c8-d3d2-11e5-8924-45a752e197a5.png">

I can look at it if it seems to you necessary. For the moment can't find where, but with a little bit of help I should be able to start.

💕

**Comment by Kyslik** [comment]
Anything new on this ? :)

**Comment by benoittgt** [comment]
Old issue. Closing for now.
