### ISSUE TITLE
Connection with apiary.io

### ISSUE THREAD

**Issue by szkrd** [danielgtaylor/aglio#240]
I can't seem to find an info about aglio: is aglio used by apiary.io? Can I trust that the warnings and errors coming from aglio will be a problem on apiary too? Is there a difference between apiary live editor and aglio? Thank you!

**Comment by zdne** [comment]
Hey @szkrd Apiary is using the same parser as Aglio ([Protagonist](https://github.com/apiaryio/protagonist)), albeit it might be running different version. 

Aglio renders the documentation from API Blueprint as Apiary does. However the two differs in the way the documentation is rendered (visual layout) even they are using the same parser. 

Unlike Aglio, Apiary is a hosted solution and benefits from integration with other tools such as Mock Server, GitHub or Dredd for testing. 

Hope this clarifies.

**Comment by szkrd** [comment]
Yes, thank you for the answer! I was mainly interested in the parser background: detecting problems before commit is a huge plus with Aglio, then after push Apiary can take over.
