### ISSUE TITLE
 parameter mock value can not contain “-”

### ISSUE THREAD

**Issue by ustory** [danielgtaylor/aglio#307]
**origin doc**
+ Parameters
    + checkIn:      2016-10-08  - checkin date
    + checkOut:     2016-10-10  - checkout date

**display doc**
checkIn string (required) Example: 2016
              10-08 - checkin date
checkOut string (required) Example: 2016
                 10-10 - checkout date

the first “-” used to separate parameter mock value and parameter description，so mock value  can not contain “-”

**Comment by kylef** [comment]
You will need to escape your values:

```apib
+ Parameters
    + checkIn: `2016-10-08` - checkin date
    + checkOut: `2016-10-10` - checkout date
```

**Comment by ustory** [comment]
have solve this issue，thanks！
