### ISSUE TITLE
URI Parameters problem

### ISSUE THREAD

**Issue by killdada** [danielgtaylor/aglio#316]
URI Parameters is not required but show required 

![1](https://cloud.githubusercontent.com/assets/16487810/21492490/4587904e-cc40-11e6-908a-482ef9d2283e.png)
![2](https://cloud.githubusercontent.com/assets/16487810/21492491/47cdb91e-cc40-11e6-8142-e3c9f5303a5e.png)
![3](https://cloud.githubusercontent.com/assets/16487810/21492492/490ed5ec-cc40-11e6-8635-63e24833b42f.png)

**Comment by herophuong** [comment]
That is because "required" is the default if we don't specify anything. Refer to the spec here:
https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-uriparameters-section

**Comment by kylef** [comment]
Yes that's correct. If you want optional for a parameter you'd need to explicitly specify this.
