### ISSUE TITLE
Rendering attributes?

### ISSUE THREAD

**Issue by Drakota** [danielgtaylor/aglio#324]
Hi, I'm new to aglio I was trying to render attributes for my documentation, but it does not work.

```
## Modify User [/users/{id}.json?{token}=API_TOKEN]
Modify any accessible fields if authorized

### Modify User [PUT]
+ Parameters
    + id: 1 (required, String) - User ID
    + token: (String) - API Token provided by the application
+ Attributes (object)
    + email : Format: john@appleseed.com (string) - Email UNIQUE
    + password : (string) - Password
    + firstname : (string) - Firstname
    + lastname : 1 (string) - Lastname
```
When trying to render this request with `aglio -i input.apib --theme-template triple -o output.html`, I don't see the attributes. Why?

Thanks for helping.

**Comment by a-rodin** [comment]
Take a look at #103

**Comment by a-rodin** [comment]
Take a look at #103.

**Comment by kylef** [comment]
There is already an issue tracking adding support for rendering the attributes. Please search existing issues before opening new ones.

Closing in favour of #103.
