### ISSUE TITLE
Path variables not showing up in the generated output

### ISSUE THREAD

**Issue by maingi4** [danielgtaylor/aglio#327]
Posted this is in stackoverflow @ http://stackoverflow.com/questions/43084514/aglio-api-blueprint-path-variables-not-showing-up

I have an API blueprint which goes something like this:

    ## Organization Users [/organizations/{id}/Users]
    
             + Parameters
             
                + id (string, required) - path variable, id of the organization.
    
    
    some text was here.
    
    ### Get Org Users [GET]
    
    some text was here.
    
    + Request (application/json)

When I run Aglio with something akin to:

    aglio --theme-variables streak  -i AppServices/Organizations.apib -o Build/AppServices.html

I get the output like:
[![No path variable][1]][1]

  [1]: https://i.stack.imgur.com/chDz7.png

Notice that the path variables are simply not present.

Other facts:

1. No warning is shown by aglio while generating the output
2. The API blueprint validates fine.
3. I tried all the themes aglio has to offer, same result.

**Comment by maingi4** [comment]
anybody? @danielgtaylor ?

**Comment by kylef** [comment]
@maingi4 The parameters section is incorrectly intended and thus showing up as raw markdown description.

I think you want something like:

```apib
## Organization Users [/organizations/{id}/Users]

+ Parameters
    + id (string, required) - path variable, id of the organization.

some text was here.

### Get Org Users [GET]

some text was here.

+ Request (application/json)
```

**Comment by maingi4** [comment]
that worked (and was embarrassing)! Thanks @danielgtaylor , great work with the tool btw.
