### ISSUE TITLE
coffe-script error

### ISSUE THREAD

**Issue by agurha** [danielgtaylor/aglio#34]
When using node module. Get error

Cannot find module 'coffee-script']
  code: 'MODULE_NOT_FOUND',

for /aglio/templates/_bootstrap-mixins.jade'. 

Maybe just not use coffee and cut out unnecessary dependency? Whats wrong with JS?

**Comment by kadishmal** [comment]
I'm bitten by this same issue. @agurha would be nice if you shared your JS code.
