### ISSUE TITLE
can't install aglio on linux

### ISSUE THREAD

**Issue by zaibon** [danielgtaylor/aglio#340]
I tried to install aglio using `sudo npm install -g aglio` but the install end up in an infinite loop with this error message
```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/aglio/node_modules/protagonist/.node-gyp/8.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/aglio/node_modules/protagonist/.node-gyp"
```

**Comment by knasim** [comment]
on Darwin i'm getting this:

`node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@7.2.1 (node-v51 ABI) (falling back to source compile with node-gyp) `

**Comment by cheyuriy** [comment]
You can try installing it with --unsafe-perm flag
