### ISSUE TITLE
Hyphens on example of string parameters cannot be escaped.

### ISSUE THREAD

**Issue by djansyle** [danielgtaylor/aglio#342]
Consider this situation.

+ Parameters
    + lastId: d26e615d-7de0-44e6-83e0-7b6937ddef33 (optional, string) - about lastId

This is how it's being rendered.
![screen shot 2017-11-16 at 9 28 46 am](https://user-images.githubusercontent.com/10968957/32869194-a3527742-cab0-11e7-866c-0f086684d61f.png)

It only take the words after the first hyphen.

**Comment by JoeNg93** [comment]
Hi, not sure if you found the solution already but enclosing the value inside \`\` will work, example:

lastId: \`d26e615d-7de0-44e6-83e0-7b6937ddef33\` (optional, string) - about lastId

**Comment by Gasol** [comment]
According to [MSON spec](https://apiblueprint.org/documentation/mson/specification.html#6-reserved-characters--keywords), The hyphens is a reserved character, Please use backtick to escape the whole value.

Related issues:
https://github.com/apiaryio/api-blueprint/issues/224
https://github.com/apiaryio/api-blueprint/issues/248
https://github.com/apiaryio/drafter/issues/697#issuecomment-491337276
