### ISSUE TITLE
URL params not rendered

### ISSUE THREAD

**Issue by MattBlack85** [danielgtaylor/aglio#354]
Hi people, I'm having a strange issue with URL params:
in the apib template I have such a definition:
`## New activation link [/newactivationlink/{email}]`

while after being converted to html I just see:
`GET /newactivationlink/`

This happens with all the URIs, does anybody have any idea why URL params aren't rendered?

**Comment by jjatria** [comment]
You are probably [missing the `Parameters` section](https://apiblueprint.org/documentation/specification.html#def-uriparameters-section) under the action. This tripped me up as well: all URI parameters must be specified in the Parameters section or they will be discarded.

```
# Foo [/{id}]

+ Parameters

    + id: `example` (string) - A description

+ Request
    ...
```

**Comment by falkorichter** [comment]
I have the same issue here:

```
## End a ride [POST /api/v1/bicycles/{bike_id}/ride/end]

+ Request (application/json)

    + Parameters:

        + bike_id: `db4fb110-7527-43f3-8d40-c3b7897270e5` (string) - The UUID of the bike
```
does not render the `bike_id` in the url:
<img width="1150" alt="Screenshot 2019-06-27 14 49 40" src="https://user-images.githubusercontent.com/50506/60267559-cd8f4a80-98ea-11e9-86fa-f4c241ad7258.png">

**Comment by jjatria** [comment]
Move the `Parameters` section up one level (so it's at the same level as `Request`).

You can see [in the docs](https://apiblueprint.org/documentation/specification.html#def-uriparameters-section) that the URI parameters are a child of the resource, not the request:

```
## End a ride [POST /api/v1/bicycles/{bike_id}/ride/end]

+ Parameters:

    + bike_id: `db4fb110-7527-43f3-8d40-c3b7897270e5` (string) - The UUID of the bike

+ Request (application/json)

...
```

**Comment by Gasol** [comment]
Please refer to answer by @jjatria
