### ISSUE TITLE
Normalize link names for both types of templates.

### ISSUE THREAD

**Issue by jgornick** [danielgtaylor/aglio#52]
If you change from a single to multiple page template, the name of the links for groups, resources, and actions also change. It would be nice if those link names were the same across the different types of templates.

It may also be nice to define a way in the markdown to better link to other resources in the document.

**Comment by danielgtaylor** [comment]
The multipage theme has been removed (for now) from the Aglio 2.0 release due to various issues. Please let me know if you'd like to see multipage support in the new theme engine.
