### ISSUE TITLE
Clarify rendering of action-specific parameters.

### ISSUE THREAD

**Issue by wkoffel** [danielgtaylor/aglio#58]
Currently, if I specify a URI parameter on my resource, I MUST include all the parameters, even if some are only relevant to a subset of the actions on that resource. (This is an [understood issue](https://github.com/apiaryio/api-blueprint/issues/79) with the specification.)

I'd prefer to have the documentation not repeat the irrelevant parameters when rendering the block for a particular action, as it's confusing to readers to see those extra params when they can't be used.  See [this discussion](https://github.com/apiaryio/api-blueprint/issues/40#issuecomment-39554781) for a lot more comments on this debate.

Any chance aglio would change the output to help make this clearer, as Apiary is supposedly doing with their doc generator?

**Comment by richardkall** [comment]
+1 - Any progress on this?

**Comment by wyattjoh** [comment]
This is a major blocker for using aglio to render our documentation. Not sure if this is an issue still with protagonist.

**Comment by zdne** [comment]
Please help me understand the problem. Is it that Aglio renders all parameters specified in the URI template for every action? 

Thus Aglio isn't following:

> - A parameter discussed in a Resource section applies to any and all nested action(s)
> - A parameter discussed in a Action section applies to to the respective action only

**Comment by wyattjoh** [comment]
The issue we're encountering is when we have a set of actions for a resource, say:

```

# Group Post

## Post Authors [/post/{post_id}/authors{?limit,offset}]

+ Parameters
  + post_id (string, required) ... ID of a post

### Create [POST]

### Retrieve [GET]

+ Parameters
  + limit (number, optional) - Limit the number of subscriptions

      Limit can range between 1 and 100 items.

      + Default: `6`
  + offset (number, optional) ... Amount to offset results by

```

I'd expect to see the following rendered out:

```
Post Authors

Create [POST] - /post/{post_id}/authors
  + post_id

Retrieve [GET] - /post/{post_id}/authors{?limit,offset}
  + post_id
  + limit
  + offset
```

Where instead I'm getting:

```
Post Authors

Create [POST] - /post/{post_id}/authors{?limit,offset}
  + post_id

Retrieve [GET] - /post/{post_id}/authors{?limit,offset}
  + limit
  + offset
```

Which from what I can see from the issues where this is discussed on the spec repo https://github.com/apiaryio/api-blueprint/issues/40#issuecomment-39315181. So I'm not sure if this again is an issue with how protaganist generates the AST or if it's just a templating/logic issue with aglio.

**Comment by neilcoles** [comment]
I agree with above post and am having the exact same issue. Although not a major blocker for me, it does make the documentation look confusing when parameters that don't apply to certain actions still appear

**Comment by zdne** [comment]
Thanks @wyattjoh this is not clear to me! 

>  it's just a templating/logic issue with aglio.

That is correct. The issue is with rendering in Aglio. Albeit, to be honest, the current state of AST makes it somewhat difficult to get it right. I am working towards fixing this on the AST level. 

Meanwhile I am reclassifying this as a bug – something that needs fixing. By any chance would you be able to look into this? Thanks!

**Comment by Chyzwar** [comment]
I have some similar issues.

When I want to declare action usining:
## ValueSet [GET /api/value-sets/{id}] 
or 
### ValueSet [GET /api/value-sets/{id}] 
Aglio do not render anything. 


Aglio also do not follow blueprint api format. 
# Group Somegorup  - in aglio # Group
# Resource                 -in Aglio ## Resource
## Action                    -in Aglio ### Action
Can someone provide clarification??


I wanted to use Aglio together with Dredd, did anyone tried?

**Comment by zdne** [comment]
@Chyzwar 

the `## ValueSet [GET /api/value-sets/{id}] ` is fairly new syntax that was just released. And as such I believe it was not accounted for in Aglio just yet. 

I believe this is fundamentally different issue that the original one posted here. I would suggest to open another issue – feature request for it. 

Regarding 

> I wanted to use Aglio together with Dredd, did anyone tried?

What you mean exactly by this? I see those two tools complementing each other however they integrated are not integrated together.

**Comment by danielgtaylor** [comment]
Thanks for the feedback everyone. I'm going to be looking into fixing this properly.

**Comment by danielgtaylor** [comment]
This should now work as expected in the latest beta. Thanks for the help everyone, and @worldspawn I've given you credit for bfe113ef1872fff13e5e9b6f8c04a2ba48dfafdd. Please try it out and let me know if there are any problems: `npm install -g aglio@beta`. The 2.0 release is coming very soon.

@wkoffel @wyattjoh @neilcoles @Chyzwar

**Comment by Chyzwar** [comment]
Thanks :)

2015-07-14 14:54 GMT+01:00 Daniel G. Taylor <notifications@github.com>:
