### ISSUE TITLE
Sidebar not rendering correctly

### ISSUE THREAD

**Issue by benkraus** [danielgtaylor/aglio#6]
When there is only 1 request defined in a URI template, only the URI template's name is shown in the sidebar, and not the request.

**Comment by Anahkiasen** [comment]
@danielgtaylor I tried `--no-theme-condense` (as per the README) `--no-theme-condense-nav` (as per the CHANGELOG) and `--no-condense` (as per this issue) but neither of the three worked, what is the name of the flag now?
