### ISSUE TITLE
Parameter name shown as 0, 1, 2, ...

### ISSUE THREAD

**Issue by twolff-iow** [danielgtaylor/aglio#65]
I am using the API blueprint preview (v0.2.2) in the Atom editor (v0.136.0) and I have used the following API description for a GET call:

```md
## GET /v1/campaigns{?ids,name}

+ Parameters

  + ids (array, optional) ... List of ids for which the campaigns are returned.
  + name (string, optional) ... A filter for the campaign name.
```

What I get in the preview window is the following.

```
0 array (optional) 
List of ids for which the campaigns are returned.

1 string (optional) 
A filter for the campaign name.
```

So, instead of the parameter names "ids" and "name", I get 0 and 1. Can you help me what is wrong?

**Comment by danielgtaylor** [comment]
This is now fixed in the latest API Blueprint Preview plugin.
