### ISSUE TITLE
aglio hangs if request body starts with ------------------------------

### ISSUE THREAD

**Issue by tinexw** [danielgtaylor/aglio#72]
If I call aglio with the following it does not return for at least 10 minutes. 

```md
FORMAT: 1A

# Test API

A test.

# POST

+ Request

    + Body

            ------------------------------107cd2e1026c
```

Calling snowcrash directly works.
It used to work with 1.16.1.
It also works if the number of `-`is reduced.

**Comment by sebastienbonami** [comment]
I encountered the same problem. As I see here https://github.com/isagalaev/highlight.js/issues/666#issuecomment-67183866, it would work with highlight.js 8.1.0. How can I just change the version of this dependency in my aglio installation?

**Comment by danielgtaylor** [comment]
@sebastienbonami just run `npm install highlight.js@8.1.0` inside of the aglio install folder and it will install that specific version. Alternatively you can fork and update the `package.json` file.

**Comment by sebastienbonami** [comment]
@danielgtaylor thank you, that's what I was looking for.

**Comment by danielgtaylor** [comment]
This is now fixed in the new theme, since it limits which formats are attempted for auto-highlighting. Release coming soon but for now it can be installed via `npm install -g aglio@beta`.
