### ISSUE TITLE
Bug: Template Stops Rendering New Updates

### ISSUE THREAD

**Issue by JemiloII** [danielgtaylor/aglio#74]
I was editing the _bootstrap-layout.jade to add styles for a form to send ajax/socket test calls to the server. It seems that no matter how many changes I do now, it remains the same. So there is a bug somewhere with a file refusing to update/rewrite.

**Comment by mjgp2** [comment]
This seems to be an issue still on 0.18.0

**Comment by janmisek** [comment]
+1

**Comment by janmisek** [comment]
This is upstream bug. Using JetBrains WebStorm and i have the issue while in mcedit everything works properly.  upstream bug: https://github.com/paulmillr/chokidar/issues/237

**Comment by janmisek** [comment]
For now workaround is to pass `{usePolling: true}` to chokidar.

**Comment by bikezilla** [comment]
Still an issue.
```
λ ~/ aglio -v
aglio 2.1.1
olio 1.2.1
λ ~/ 

Anyone else? Fix, workaround?

```

**Comment by danielgtaylor** [comment]
I'm re-opening this issue and will investigate the suggested workarounds.
