### ISSUE TITLE
Resource-wide parameters are not shown in all actions

### ISSUE THREAD

**Issue by frank-weindel** [danielgtaylor/aglio#79]
As mentioned [here](https://github.com/apiaryio/api-blueprint/issues/79):
> A parameter discussed in a Resource section applies to any and all nested action(s)

I'm attempting to use resource parameter definitions to describe parameters that are acceptable in all actions of the resource. However the only time these resource parameters are shown is on actions that do not specify any parameter section.

I'd expect (when rendered) that these parameters either appear alone right under the resource description or get mixed in with the parameter section of each action.

Is there any way to get either of these things to happen?

**Comment by richardkall** [comment]
+1

**Comment by danielgtaylor** [comment]
As of bfe113ef1872fff13e5e9b6f8c04a2ba48dfafdd this is now implemented properly in the default theme. You can install the beta via `npm install -g aglio@beta`.
