### ISSUE TITLE
Add support for other static files in watch mode

### ISSUE THREAD

**Issue by martinheidegger** [danielgtaylor/aglio#81]
Currently when starting in the watch mode other resources  (like images) don't work because they are not served from the server that is started. I read through the code thinking on how to fix it and my recommendation would be to ditch it in favour of https://github.com/tapio/live-server

**Comment by danielgtaylor** [comment]
@martinheidegger, how exactly would you use this? Honestly something like [grunt-aglio](https://www.npmjs.com/package/grunt-aglio) along with Grunt's watching abilities might be better?

**Comment by martinheidegger** [comment]
I think I wasn't clear about the issue:

The server will always [only serve the html file](https://github.com/danielgtaylor/aglio/blob/master/src/bin.coffee#L88) never any of the other static asses. So if you link to an image file in the markdown code the image will not be shown because the server does not return any image.

**Comment by gerardobort** [comment]
:+1:

**Comment by maximeaubaret** [comment]
I've made a simple change in #112. This was bugging me as well.

**Comment by danielgtaylor** [comment]
The PR in #112 has been merged and this feature will be in the next release.
