### ISSUE TITLE
Using a template causes error to disappear

### ISSUE THREAD

**Issue by FrankyBoy** [danielgtaylor/aglio#82]
Hi!

I have some faulty doc, which has an unexpected header. If I compile like so ... ```aglio -i docs.md -o index.html```, I get a warning in the console and a document is produced. The message is:

    >> Line 1813: unexpected header block, expected a group, resource or an action definition, e.g. '#Group <name>', '# <re
    source name> [<URI>]' or '# <HTTP method> <URI>' (warning code 5)
    >> Line 1815: ignoring unrecognized block (warning code 5)
    >> Line 1816: ignoring unrecognized block (warning code 5)

however if I add a ``` --template default-collapsible``` the error disappears, and no output is generated. I'll try to boil this down to some minimal case because the doc is pretty big and for internal use only :/

**Comment by danielgtaylor** [comment]
@FrankyBoy thanks for the bug report. I'll try to reproduce and track down what's happening.

**Comment by danielgtaylor** [comment]
I am unable to reproduce this issue using the newly released Aglio 2.0. All warnings are reported properly. Please give it a try and let me know if you still have problems!
