### ISSUE TITLE
Custom template in local dir not found

### ISSUE THREAD

**Issue by dometec** [danielgtaylor/aglio#83]
I created a template but it can't be found from jade:

```bash
[dometec@localhost apis]$ ll /home/dometec/git/OsysTransferFrotend/apis/bravodriver.jade
-rw-r--r-- 1 dometec dometec 8548  7 feb 19.35 /home/dometec/git/OsysTransferFrotend/apis/bravodriver.jade
[dometec@localhost apis]$ aglio -t /home/dometec/git/OsysTransferFrotend/apis/bravodriver.jade -i api.md -o api.html
>> {"errno":34,"code":"ENOENT","path":"/home/dometec/git/OsysTransferFrotend/apis/bravodriver.jade","syscall":"open"}
[dometec@localhost apis]$
```

**Comment by danielgtaylor** [comment]
@dometec I've had a chance to try this myself and both relative and absolute paths are working for me. Can you tell me more about your setup? What version of Node.js? What operating system? Are you using the latest release of Aglio? Is there anything special about that path on your system?

**Comment by dometec** [comment]
I daniel, you rigth, below the details:

```
[dometec@localhost api]$ node -v
v0.10.33

[dometec@localhost api]$ cat /etc/redhat-release 
Fedora release 21 (Twenty One)

[dometec@localhost api]$ uname -a
Linux localhost.localdomain 3.18.5-201.fc21.x86_64 #1 SMP Mon Feb 2 21:00:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[dometec@localhost api]$ cat /usr/lib/node_modules/aglio/package.json  | grep \"version\"
  "version": "1.17.1",
```

Here are some test. The templates is on the same dir of md file:

[dometec@localhost api]$ aglio -t bravodriver -i api.md -o out.html
>> {"errno":34,"code":"ENOENT","path":"/usr/lib/node_modules/aglio/templates/bravodriver.jade","syscall":"open"}

[dometec@localhost api]$ aglio -t ./bravodriver -i api.md -o out.html
>> {"errno":34,"code":"ENOENT","path":"/usr/lib/node_modules/aglio/templates/bravodriver.jade","syscall":"open"}

[dometec@localhost api]$ aglio -t /home/dometec/git/OsysTransferFrotend/api/bravodriver -i api.md -o out.html
>> {"errno":34,"code":"ENOENT","path":"/usr/lib/node_modules/aglio/templates/home/dometec/git/OsysTransferFrotend/api/bravodriver.jade","syscall":"open"}

It work only if I put the template in /usr/lib/node_modules/aglio/templates/ folder and I do:
[dometec@localhost api]$ aglio -t bravodriver -i api.md -o out.html
[dometec@localhost api]$

**Comment by switzersc** [comment]
I'm having the same problem. Same node version as dometec (v0.10.33) but on Mac OS Mavericks 10.9.5.

**Comment by switzersc** [comment]
Nevermind - I realized the problem was _not_ that the template wasn't found in the local directory, but that another file that my local template was _extending_ could not be found (I had a typo in the name).

**Comment by danielgtaylor** [comment]
@dometec please try again with Aglio 2.0 and let me know if it's still an issue. It has a couple of fixes related to path handling. Please re-open this issue if it still happens.
