### ISSUE TITLE
Nav buttons doesn't work with own collapsible and multipage theme

### ISSUE THREAD

**Issue by leutrimhusaj** [danielgtaylor/aglio#87]
I have created a new theme that is collapsible and supports multipage. (combined the two default templates)

But the navigation links for a specific group can not open the data-target (where all the available api methods are defined).

The Problem is that the containers are marked with an id like "page:test-api-menu" and the link items have a property "data-target="#page_id-api-menu".

Our local fix is like replacing the colon after "page" (page:test-api-menu) with and underline (page_test-api-menu) just for the data-targets and id property for the navigation.

The main content items can contain the colon and it works.
But maybe you have a better idea for solving this problem.

**Comment by danielgtaylor** [comment]
Thanks for the bug report. Due to various issues the multipage theme has been removed for the 2.0 release, and may be added in again later with an attempt being made to prevent the sort of issues that cropped up with the 1.x multipage template.
