### ISSUE TITLE
Verbose mode / logging

### ISSUE THREAD

**Issue by sebastienbonami** [danielgtaylor/aglio#92]
Hi, running aglio with a new version of our blueprint at work hangs indefinitely without any output. Is there a way to have verbosity or is there a log somewhere?

**Comment by danielgtaylor** [comment]
@sebastienbonami not at the moment, but a new version I'm working on in a branch allows for benchmarking, which prints out information on each step being performed. It will be released in the near future.

Until then, it sounds like this might be related to #72 where you also left a comment. Maybe also #78. Are you on Windows?

**Comment by sebastienbonami** [comment]
@danielgtaylor ok and my problem was indeed the same as #72 and I installed a previous version of highlish.js so I'm not blocked anymore.

I'm on Ubuntu by the way.

**Comment by danielgtaylor** [comment]
You can now use `BENCHMARK=1 aglio ....` and it will print out step and timing information. This should help with debugging problems. Let me know if you would like more logging.
