### ISSUE TITLE
Problem rendering images from yUML

### ISSUE THREAD

**Issue by sebastienbonami** [danielgtaylor/aglio#93]
Hi, the problem occurs with aglio v1.17.0 (and v1.17.1 also). It doesn't occur with v1.16.2.

##### Line in Markdown file:
```
![Alt text](http://yuml.me/diagram/scruffy/class/[Administrator]-^[Person], [Person]-^[Party])
```

##### HTML outputted with v1.16.2:
```
<p><img src="http://yuml.me/diagram/scruffy/class/[Administrator]-^[Person], [Person]-^[Party]" alt="Alt text"></p>
```

##### HTML outputted with v1.17.0:
```
<p>![Alt text](<a href="http://yuml.me/diagram/scruffy/class/[Administrator]-">http://yuml.me/diagram/scruffy/class/[Administrator]-</a><sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup>, [Person]-<sup class="footnote-ref"><a href="#fn2" id="fnref2">[2]</a></sup>)</p>
<hr class="footnotes-sep">
<section class="footnotes">
<ol class="footnotes-list">
<li id="fn1"  class="footnote-item"><p>Person <a href="#fnref1" class="footnote-backref">↩</a></p>
</li>
<li id="fn2"  class="footnote-item"><p>Party <a href="#fnref2" class="footnote-backref">↩</a></p>
</li>
</ol>
</section>
```

##### Result with v1.16.2:
![image](https://cloud.githubusercontent.com/assets/7561088/6702006/cf031fec-ccfa-11e4-829d-0ed4d88a6dfd.png)

##### Result with v1.17.0:
![image](https://cloud.githubusercontent.com/assets/7561088/6702037/67852904-ccfb-11e4-98a8-c69a77996902.png)

**Comment by danielgtaylor** [comment]
@sebastienbonami have you tried URL-encoding the URL? Those are technically not valid characters. It looks like maybe the `marked` module automatically did this in the past? I'll look into this a bit.

**Comment by puzrin** [comment]
URLs with spaces should be quoted with `< >` or spaces should be escaped with `\` (see commonmark spec). In current markup link is not recognized and text is rendered as footnotes & sup.

**Comment by sebastienbonami** [comment]
@danielgtaylor @puzrin thank you, using `< >` works.

**Comment by sebastienbonami** [comment]
@danielgtaylor @puzrin I was wondering, do you know a good tool to detect these kind of problems? Like a lint-like behavior.

**Comment by puzrin** [comment]
@sebastienbonami I've seen [markdownlint](https://github.com/DavidAnson/markdownlint) project in dependencies, but can't say anythings about it.
